name: Java Jdk SetUp CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v3.14.1
      with:
        java-version: '17'
        distribution: 'temurin'
