name: Demo - Manual Trigger via UI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: echo "Build stage - manually triggered via UI by ${{ github.actor }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Stage
        run: echo "Deploy stage - manually triggered via UI"

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Test Stage
        run: echo " Test stage - manually triggered via UI"
