name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js environment
      uses: actions/setup-node@v3.9.1
      with:
        node-version: '22'
