name: Demo - Pull Request Event with Build/Deploy/Test
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: echo "Build stage for pull request event by ${{ github.actor }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Stage
        run: echo "Deploy stage for pull request event"

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Test Stage
        run: echo "Test stage for pull request event"
