name: Demo - Pull Request Review Event with Build/Deploy/Test
on:
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: echo "Build stage for PR review event by ${{ github.actor }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Stage
        run: echo "Deploy stage for PR review event"

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Test Stage
        run: echo "Test stage for PR review event"
