name: Demo - Push Event with Filters
on:
  push:
    branches:
      - main    
      - 'release-*'     
    branches-ignore:
      - 'docs-*'        

    tags:
      - 'v*'             
    tags-ignore:
      - 'beta-*'          

    paths:
      - 'src/**'         
      - '!src/experimental/**' 
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: echo "Build stage - push to ${{ github.ref }} by ${{ github.actor }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Stage
        run: echo " Deploy stage - push to ${{ github.ref }}"

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Test Stage
        run: echo " Test stage - push to ${{ github.ref }}"
