name: Demo - Scheduled Workflow (Cron Job)
on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: echo "Build stage running on schedule - triggered at $(date -u)"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Stage
        run: echo " Deploy stage running on schedule - triggered at $(date -u)"

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Test Stage
        run: echo " Test stage running on schedule - triggered at $(date -u)"
